from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.sql import func

from database import Base

# This class maps Python attributes to columns in the PostgreSQL jobs table.
class Job(Base):
    # PostgreSQL table used to store job postings.
    __tablename__ = "jobs"

    # The ID is generated by the database and uniquely identifies each job.
    # Column(type, ...) describes the database type and its constraints.
    id = Column(Integer, primary_key=True, index=True)
    # These fields are required when a job is created or updated.
    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    # PostgreSQL assigns the creation time when the row is inserted.
    created_at = Column(DateTime(timezone=True), server_default=func.now())